// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:locale?/collections/:handle.json": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/blogs/:blogHandle/:handle": {
    params: {
      "locale"?: string;
      "blogHandle": string;
      "handle": string;
    };
  };
  "/:locale?/products/:handle.json": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/api/predictive-search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/recommendations": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/collections/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/account/authorize": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/product-by-id": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/articles/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/products/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/account/logout": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/discounts/:code": {
    params: {
      "locale"?: string;
      "code": string;
    };
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/:locale?/account/login": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/collection": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/countries": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/blogs/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/pages/:handle": {
    params: {
      "locale"?: string;
      "handle": string;
    };
  };
  "/:locale?/api/articles": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/products": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/redirect": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/klaviyo": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/product": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/reviews": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/api/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/product-feed.xml": {
    params: {};
  };
  "/:locale?/account": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/orders/:id": {
    params: {
      "locale"?: string;
      "id": string;
    };
  };
  "/:locale?/account/addresses": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/profile": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/account/*": {
    params: {
      "locale"?: string;
      "*": string;
    };
  };
  "/:locale?": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/search": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart": {
    params: {
      "locale"?: string;
    };
  };
  "/:locale?/cart/:lines": {
    params: {
      "locale"?: string;
      "lines": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/api/edit": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:locale?/collections/:handle.json" | "/:locale?/blogs/:blogHandle/:handle" | "/:locale?/products/:handle.json" | "/:locale?/api/predictive-search" | "/:locale?/api/recommendations" | "/:locale?/collections/:handle" | "/:locale?/account/authorize" | "/:locale?/api/product-by-id" | "/:locale?/articles/:handle" | "/:locale?/products/:handle" | "/:locale?/account/logout" | "/:locale?/discounts/:code" | "/sitemap/:type/:page.xml" | "/:locale?/account/login" | "/:locale?/api/collection" | "/:locale?/api/countries" | "/:locale?/blogs/:handle" | "/:locale?/pages/:handle" | "/:locale?/api/articles" | "/:locale?/api/products" | "/:locale?/api/redirect" | "/:locale?/api/klaviyo" | "/:locale?/api/product" | "/:locale?/api/reviews" | "/:locale?/api/search" | "/:locale?/api/cart" | "/product-feed.xml" | "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*" | "/:locale?" | "/:locale?/search" | "/:locale?/cart" | "/:locale?/cart/:lines" | "/sitemap.xml" | "/robots.txt" | "/api/edit" | "/*" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/($locale).collections.$handle[.]json.tsx": {
    id: "routes/($locale).collections.$handle[.]json";
    page: "/:locale?/collections/:handle.json";
  };
  "routes/($locale).blogs.$blogHandle.$handle.tsx": {
    id: "routes/($locale).blogs.$blogHandle.$handle";
    page: "/:locale?/blogs/:blogHandle/:handle";
  };
  "routes/($locale).products.$handle[.]json.tsx": {
    id: "routes/($locale).products.$handle[.]json";
    page: "/:locale?/products/:handle.json";
  };
  "routes/($locale).api.predictive-search.tsx": {
    id: "routes/($locale).api.predictive-search";
    page: "/:locale?/api/predictive-search";
  };
  "routes/($locale).api.recommendations.tsx": {
    id: "routes/($locale).api.recommendations";
    page: "/:locale?/api/recommendations";
  };
  "routes/($locale).collections.$handle.tsx": {
    id: "routes/($locale).collections.$handle";
    page: "/:locale?/collections/:handle";
  };
  "routes/($locale).account_.authorize.tsx": {
    id: "routes/($locale).account_.authorize";
    page: "/:locale?/account/authorize";
  };
  "routes/($locale).api.product-by-id.tsx": {
    id: "routes/($locale).api.product-by-id";
    page: "/:locale?/api/product-by-id";
  };
  "routes/($locale).articles.$handle.tsx": {
    id: "routes/($locale).articles.$handle";
    page: "/:locale?/articles/:handle";
  };
  "routes/($locale).products.$handle.tsx": {
    id: "routes/($locale).products.$handle";
    page: "/:locale?/products/:handle";
  };
  "routes/($locale).account_.logout.ts": {
    id: "routes/($locale).account_.logout";
    page: "/:locale?/account/logout";
  };
  "routes/($locale).discounts.$code.tsx": {
    id: "routes/($locale).discounts.$code";
    page: "/:locale?/discounts/:code";
  };
  "routes/sitemap.$type.$page[.xml].tsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/($locale).account_.login.tsx": {
    id: "routes/($locale).account_.login";
    page: "/:locale?/account/login";
  };
  "routes/($locale).api.collection.tsx": {
    id: "routes/($locale).api.collection";
    page: "/:locale?/api/collection";
  };
  "routes/($locale).api.countries.tsx": {
    id: "routes/($locale).api.countries";
    page: "/:locale?/api/countries";
  };
  "routes/($locale).blogs.$handle.tsx": {
    id: "routes/($locale).blogs.$handle";
    page: "/:locale?/blogs/:handle";
  };
  "routes/($locale).pages.$handle.tsx": {
    id: "routes/($locale).pages.$handle";
    page: "/:locale?/pages/:handle";
  };
  "routes/($locale).api.articles.tsx": {
    id: "routes/($locale).api.articles";
    page: "/:locale?/api/articles";
  };
  "routes/($locale).api.products.tsx": {
    id: "routes/($locale).api.products";
    page: "/:locale?/api/products";
  };
  "routes/($locale).api.redirect.tsx": {
    id: "routes/($locale).api.redirect";
    page: "/:locale?/api/redirect";
  };
  "routes/($locale).api.klaviyo.tsx": {
    id: "routes/($locale).api.klaviyo";
    page: "/:locale?/api/klaviyo";
  };
  "routes/($locale).api.product.tsx": {
    id: "routes/($locale).api.product";
    page: "/:locale?/api/product";
  };
  "routes/($locale).api.reviews.tsx": {
    id: "routes/($locale).api.reviews";
    page: "/:locale?/api/reviews";
  };
  "routes/($locale).api.search.tsx": {
    id: "routes/($locale).api.search";
    page: "/:locale?/api/search";
  };
  "routes/($locale).api.cart.tsx": {
    id: "routes/($locale).api.cart";
    page: "/:locale?/api/cart";
  };
  "routes/[product-feed.xml].tsx": {
    id: "routes/[product-feed.xml]";
    page: "/product-feed.xml";
  };
  "routes/($locale).account.tsx": {
    id: "routes/($locale).account";
    page: "/:locale?/account" | "/:locale?/account/orders" | "/:locale?/account/orders/:id" | "/:locale?/account/addresses" | "/:locale?/account/profile" | "/:locale?/account/*";
  };
  "routes/($locale).account.orders._index.tsx": {
    id: "routes/($locale).account.orders._index";
    page: "/:locale?/account/orders";
  };
  "routes/($locale).account.orders.$id.tsx": {
    id: "routes/($locale).account.orders.$id";
    page: "/:locale?/account/orders/:id";
  };
  "routes/($locale).account.addresses.tsx": {
    id: "routes/($locale).account.addresses";
    page: "/:locale?/account/addresses";
  };
  "routes/($locale).account.profile.tsx": {
    id: "routes/($locale).account.profile";
    page: "/:locale?/account/profile";
  };
  "routes/($locale).account.$.tsx": {
    id: "routes/($locale).account.$";
    page: "/:locale?/account/*";
  };
  "routes/($locale)._index.tsx": {
    id: "routes/($locale)._index";
    page: "/:locale?";
  };
  "routes/($locale).search.tsx": {
    id: "routes/($locale).search";
    page: "/:locale?/search";
  };
  "routes/($locale).cart.tsx": {
    id: "routes/($locale).cart";
    page: "/:locale?/cart" | "/:locale?/cart/:lines";
  };
  "routes/($locale).cart.$lines.tsx": {
    id: "routes/($locale).cart.$lines";
    page: "/:locale?/cart/:lines";
  };
  "routes/[sitemap.xml].tsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/api.edit.tsx": {
    id: "routes/api.edit";
    page: "/api/edit";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/jeremygabriel/Development/packdigital/forks/pack-hydrogen-theme-blueprint/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};