import {containerSettings} from '~/settings/container';
import {
  COLOR_PICKER_DEFAULTS,
  COLOR_SCHEMA_DEFAULT_VALUE,
} from '~/settings/common';

export function Schema() {
  return {
    category: 'Text',
    label: 'Marquee',
    key: 'marquee',
    previewSrc:
      'https://cdn.shopify.com/s/files/1/0629/5519/2520/files/marquee-section-preview.jpg?v=1745289682',
    fields: [
      {
        label: 'Content Items',
        name: 'contentItems',
        component: 'group-list',
        itemProps: {
          label: '{{item.text}}',
        },
        description: 'Marquee cycles through each item in the list',
        fields: [
          {
            label: 'Text',
            name: 'text',
            component: 'rich-text',
            description: 'Do not using headings for marquee text',
          },
        ],
        defaultValue: [
          {
            text: '<p>Lorem ipsum dolor sit amet consectetur adipiscing elit</p>',
          },
        ],
      },
      {
        label: 'Content Settings',
        name: 'content',
        component: 'group',
        description:
          'Background color, text color, font, font size, letter spacing, vertical padding, spacing between items',
        fields: [
          {
            label: 'Background Color',
            name: 'bgColor',
            component: 'color',
            colors: COLOR_PICKER_DEFAULTS,
          },
          {
            label: 'Text Color',
            name: 'textColor',
            component: 'color',
            colors: COLOR_PICKER_DEFAULTS,
          },
          {
            label: 'Font',
            name: 'font',
            component: 'radio-group',
            direction: 'horizontal',
            variant: 'radio',
            options: [
              {label: 'Heading', value: 'font-heading'},
              {label: 'Body', value: 'font-sans'},
            ],
          },
          {
            label: 'Uppercase',
            name: 'uppercase',
            component: 'toggle',
            toggleLabels: {
              true: 'On',
              false: 'Off',
            },
          },
          {
            label: 'Font Size (desktop)',
            name: 'fontSizeDesktop',
            component: 'select',
            options: [
              {label: '10px', value: 'lg:text-[10px]/[10px]'},
              {label: '12px', value: 'lg:text-[12px]/[12px]'},
              {label: '14px', value: 'lg:text-[14px]/[14px]'},
              {label: '16px', value: 'lg:text-[16px]/[16px]'},
              {label: '18px', value: 'lg:text-[18px]/[18px]'},
              {label: '20px', value: 'lg:text-[20px]/[20px]'},
              {label: '24px', value: 'lg:text-[24px]/[24px]'},
              {label: '30px', value: 'lg:text-[30px]/[30px]'},
              {label: '36px', value: 'lg:text-[36px]/[36px]'},
              {label: '48px', value: 'lg:text-[48px]/[48px]'},
              {label: '60px', value: 'lg:text-[60px]/[60px]'},
              {label: '72px', value: 'lg:text-[72px]/[72px]'},
              {label: '96px', value: 'lg:text-[96px]/[96px]'},
            ],
          },
          {
            label: 'Font Size (tablet)',
            name: 'fontSizeTablet',
            component: 'select',
            options: [
              {label: '10px', value: 'md:text-[10px]/[10px]'},
              {label: '12px', value: 'md:text-[12px]/[12px]'},
              {label: '14px', value: 'md:text-[14px]/[14px]'},
              {label: '16px', value: 'md:text-[16px]/[16px]'},
              {label: '18px', value: 'md:text-[18px]/[18px]'},
              {label: '20px', value: 'md:text-[20px]/[20px]'},
              {label: '24px', value: 'md:text-[24px]/[24px]'},
              {label: '30px', value: 'md:text-[30px]/[30px]'},
              {label: '36px', value: 'md:text-[36px]/[36px]'},
              {label: '48px', value: 'md:text-[48px]/[48px]'},
              {label: '60px', value: 'md:text-[60px]/[60px]'},
              {label: '72px', value: 'md:text-[72px]/[72px]'},
              {label: '96px', value: 'md:text-[96px]/[96px]'},
            ],
          },
          {
            label: 'Font Size (mobile)',
            name: 'fontSizeMobile',
            component: 'select',
            options: [
              {label: '10px', value: 'text-[10px]/[10px]'},
              {label: '12px', value: 'text-[12px]/[12px]'},
              {label: '14px', value: 'text-[14px]/[14px]'},
              {label: '16px', value: 'text-[16px]/[16px]'},
              {label: '18px', value: 'text-[18px]/[18px]'},
              {label: '20px', value: 'text-[20px]/[20px]'},
              {label: '24px', value: 'text-[24px]/[24px]'},
              {label: '30px', value: 'text-[30px]/[30px]'},
              {label: '36px', value: 'text-[36px]/[36px]'},
              {label: '48px', value: 'text-[48px]/[48px]'},
              {label: '60px', value: 'text-[60px]/[60px]'},
              {label: '72px', value: 'text-[72px]/[72px]'},
              {label: '96px', value: 'text-[96px]/[96px]'},
            ],
          },
          {
            label: 'Letter Spacing',
            name: 'letterSpacing',
            component: 'select',
            options: [
              {label: 'Tighter', value: 'tracking-tighter'},
              {label: 'Tight', value: 'tracking-tight'},
              {label: 'Normal', value: 'tracking-normal'},
              {label: 'Wide', value: 'tracking-wide'},
              {label: 'Wider', value: 'tracking-wider'},
              {label: 'Widest', value: 'tracking-widest'},
            ],
          },
          {
            label: 'Vertical Padding (desktop)',
            name: 'yPaddingDesktop',
            component: 'select',
            options: [
              {label: '0px', value: 'lg:py-[0px]'},
              {label: '2px', value: 'lg:py-[2px]'},
              {label: '4px', value: 'lg:py-[4px]'},
              {label: '6px', value: 'lg:py-[6px]'},
              {label: '8px', value: 'lg:py-[8px]'},
              {label: '10px', value: 'lg:py-[10px]'},
              {label: '12px', value: 'lg:py-[12px]'},
              {label: '14px', value: 'lg:py-[14px]'},
              {label: '16px', value: 'lg:py-[16px]'},
              {label: '18px', value: 'lg:py-[18px]'},
              {label: '20px', value: 'lg:py-[20px]'},
              {label: '24px', value: 'lg:py-[24px]'},
              {label: '32px', value: 'lg:py-[32px]'},
              {label: '40px', value: 'lg:py-[40px]'},
              {label: '48px', value: 'lg:py-[48px]'},
              {label: '56px', value: 'lg:py-[56px]'},
              {label: '64px', value: 'lg:py-[64px]'},
            ],
          },
          {
            label: 'Vertical Padding (tablet)',
            name: 'yPaddingTablet',
            component: 'select',
            options: [
              {label: '0px', value: 'md:py-[0px]'},
              {label: '2px', value: 'md:py-[2px]'},
              {label: '4px', value: 'md:py-[4px]'},
              {label: '6px', value: 'md:py-[6px]'},
              {label: '8px', value: 'md:py-[8px]'},
              {label: '10px', value: 'md:py-[10px]'},
              {label: '12px', value: 'md:py-[12px]'},
              {label: '14px', value: 'md:py-[14px]'},
              {label: '16px', value: 'md:py-[16px]'},
              {label: '18px', value: 'md:py-[18px]'},
              {label: '20px', value: 'md:py-[20px]'},
              {label: '24px', value: 'md:py-[24px]'},
              {label: '32px', value: 'md:py-[32px]'},
              {label: '40px', value: 'md:py-[40px]'},
              {label: '48px', value: 'md:py-[48px]'},
              {label: '56px', value: 'md:py-[56px]'},
              {label: '64px', value: 'md:py-[64px]'},
            ],
          },
          {
            label: 'Vertical Padding (mobile)',
            name: 'yPaddingMobile',
            component: 'select',
            options: [
              {label: '0px', value: 'py-[0px]'},
              {label: '2px', value: 'py-[2px]'},
              {label: '4px', value: 'py-[4px]'},
              {label: '6px', value: 'py-[6px]'},
              {label: '8px', value: 'py-[8px]'},
              {label: '10px', value: 'py-[10px]'},
              {label: '12px', value: 'py-[12px]'},
              {label: '14px', value: 'py-[14px]'},
              {label: '16px', value: 'py-[16px]'},
              {label: '18px', value: 'py-[18px]'},
              {label: '20px', value: 'py-[20px]'},
              {label: '24px', value: 'py-[24px]'},
              {label: '32px', value: 'py-[32px]'},
              {label: '40px', value: 'py-[40px]'},
              {label: '48px', value: 'py-[48px]'},
              {label: '56px', value: 'py-[56px]'},
              {label: '64px', value: 'py-[64px]'},
            ],
          },
          {
            label: 'Spacing Between Content Items',
            name: 'spacing',
            component: 'select',
            options: [
              {label: '0px', value: 'pl-[0px]'},
              {label: '8px', value: 'pl-[8px]'},
              {label: '10px', value: 'pl-[10px]'},
              {label: '12px', value: 'pl-[12px]'},
              {label: '16px', value: 'pl-[16px]'},
              {label: '20px', value: 'pl-[20px]'},
              {label: '24px', value: 'pl-[24px]'},
              {label: '32px', value: 'pl-[32px]'},
              {label: '40px', value: 'pl-[40px]'},
              {label: '48px', value: 'pl-[48px]'},
              {label: '56px', value: 'pl-[56px]'},
              {label: '64px', value: 'pl-[64px]'},
              {label: '72px', value: 'pl-[72px]'},
              {label: '80px', value: 'pl-[80px]'},
              {label: '96px', value: 'pl-[96px]'},
              {label: '112px', value: 'pl-[112px]'},
              {label: '128px', value: 'pl-[128px]'},
            ],
          },
        ],
        defaultValue: {
          bgColor: COLOR_SCHEMA_DEFAULT_VALUE.primary,
          textColor: COLOR_SCHEMA_DEFAULT_VALUE.white,
          uppercase: false,
          fontSizeDesktop: 'lg:text-[24px]/[24px]',
          fontSizeTablet: 'md:text-[20px]/[20px]',
          fontSizeMobile: 'text-[16px]/[16px]',
          letterSpacing: 'tracking-wider',
          font: 'font-sans',
          yPaddingDesktop: 'lg:py-[16px]',
          yPaddingTablet: 'md:py-[12px]',
          yPaddingMobile: 'py-[8px]',
          spacing: 'pl-[48px]',
        },
      },
      {
        label: 'Marquee Settings',
        name: 'marquee',
        component: 'group',
        description:
          'Direction, speed, pause on hover/click, enable gradient, gradient width',
        fields: [
          {
            label: 'Direction',
            name: 'direction',
            component: 'radio-group',
            direction: 'horizontal',
            variant: 'radio',
            options: [
              {label: 'Left', value: 'left'},
              {label: 'Right', value: 'right'},
            ],
          },
          {
            label: 'Speed',
            name: 'speed',
            component: 'number',
            description: 'Pixels per second',
          },
          {
            label: 'Pause on Hover',
            name: 'pauseOnHover',
            component: 'toggle',
            toggleLabels: {
              true: 'On',
              false: 'Off',
            },
          },
          {
            label: 'Pause on Click',
            name: 'pauseOnClick',
            component: 'toggle',
            toggleLabels: {
              true: 'On',
              false: 'Off',
            },
          },
          {
            label: 'Enable Gradient',
            name: 'enabledGradient',
            component: 'toggle',
            toggleLabels: {
              true: 'On',
              false: 'Off',
            },
            description: 'Shows a gradient on either side of the marquee',
          },
          {
            label: 'Gradient Width',
            name: 'gradientWidth',
            component: 'number',
            description: 'The width of the gradient on either side in px',
          },
        ],
        defaultValue: {
          direction: 'left',
          speed: 50,
          pauseOnHover: false,
          pauseOnClick: false,
          enabledGradient: true,
          gradientWidth: 100,
        },
      },
      {
        label: 'Section Settings',
        name: 'section',
        component: 'group',
        description: 'Vertical padding',
        fields: [
          {
            label: 'Vertical Padding',
            name: 'hasYPadding',
            component: 'toggle',
            description: 'Adds default vertical padding around section',
            toggleLabels: {
              true: 'On',
              false: 'Off',
            },
          },
        ],
        defaultValue: {
          hasYPadding: false,
        },
      },
      containerSettings(),
    ],
  };
}
