export interface SearchSettings {
  results: {
    collectionsEnabled: boolean;
    noResultsText: string;
  };
  input: {
    characterMin: number;
  };
  autocomplete: {
    enabled: boolean;
    heading: string;
    limit: number;
  };
  suggestions: {
    enabled: boolean;
    heading: string;
    terms: string[];
  };
}

export default {
  label: 'Search',
  name: 'search',
  component: 'group',
  description: 'Search results, input, autocomplete, suggestions',
  fields: [
    {
      label: 'Search Results (Drawer)',
      name: 'results',
      component: 'group',
      description:
        'Note: Settings for search results page on filters, sort, pagination, product item, and promotions is shared with collections.\nSee: Site Settings > Collection',
      fields: [
        {
          label: 'Collection Search Enabled',
          name: 'collectionsEnabled',
          component: 'toggle',
          toggleLabels: {
            true: 'On',
            false: 'Off',
          },
        },
        {
          label: 'No Results Text',
          name: 'noResultsText',
          component: 'text',
        },
      ],
      defaultValue: {
        noResultsText: 'No results found.',
      },
    },
    {
      label: 'Search Input',
      name: 'input',
      component: 'group',
      description: 'Character minimum',
      fields: [
        {
          label: 'Character Minimum',
          name: 'characterMin',
          component: 'number',
          description:
            'Minimum number of characters for search input to trigger a search',
        },
      ],
      defaultValue: {
        characterMin: 3,
      },
    },
    {
      label: 'Search Autocomplete',
      name: 'autocomplete',
      component: 'group',
      description:
        'Autogenerated list of suggested search terms matching current input',
      fields: [
        {
          label: 'Enabled',
          name: 'enabled',
          component: 'toggle',
          toggleLabels: {
            true: 'On',
            false: 'Off',
          },
        },
        {
          label: 'Heading',
          name: 'heading',
          component: 'text',
        },
        {
          label: 'Limit',
          name: 'limit',
          component: 'number',
          description: 'Max of 10',
        },
      ],
      defaultValue: {
        enabled: true,
        heading: 'Suggestions',
        limit: 5,
      },
    },
    {
      label: 'Search Suggestions',
      name: 'suggestions',
      component: 'group',
      description:
        'Preset list of suggested search terms visible only when there are no results or search input',
      fields: [
        {
          label: 'Enabled',
          name: 'enabled',
          component: 'toggle',
          toggleLabels: {
            true: 'On',
            false: 'Off',
          },
        },
        {
          label: 'Heading',
          name: 'heading',
          component: 'text',
        },
        {
          label: 'Terms',
          name: 'terms',
          component: 'list',
          field: {
            component: 'text',
          },
        },
      ],
      defaultValue: {
        enabled: true,
        heading: 'Top Searches',
        terms: ['T-Shirt', 'Sweatshirt', 'Jacket'],
      },
    },
  ],
};
